config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  def tag_list
    tags.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{ |s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

#   def tag_list
#     self.tags.collect do |tag|
#       tag.name
#     end.join(", ")
#   end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    @comments = Comment.all
    @tags = Tag.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    flash.notice = "Article '#{@article.title}' Created!"
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
    flash.notice = "Article '#{@article.title}' destroyed!"
    redirect_to articles_path
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    flash.notice = "Article '#{@article.title}' Updated!"
    redirect_to article_path(@article)
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :tag_list)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save
    flash.notice = "Your comment created"
    redirect_to article_path(@comment.article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save
    flash.notice = "New tag created"
    redirect_to tags_path
  end

  def destroy
    @tag = Tag.find(params[:id])
    if @tag.destroy
    flash.notice = "Tag '#{@tag.name}' destroyed!"
    redirect_to tags_path
    end
  end

  private

  def comment_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by "<%= comment.author_name %>"</h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> ago</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :article_title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render partial: 'form' %>

<%= link_to "<< Back to Articles List", articles_path %>

app/views/articles/index.html.erb
<h1>Articles (<%= @articles.all.count %>)</h1>
<h4>Tags:
<% @tags.each do |tag| %>
  <%= link_to tag.name, tag_path(tag) %>
<% end %>
</h4>
<div><% @articles.each do |article| %>
    <p>
      <strong>
        <%= link_to article.title, article_path(article),
                    class: 'article_title',
                    id: "article_#{article.id}" %>
        </strong>  
        (<%= article.comments.count %>)
    </p>
    <p><%= article.body %></p>
    <br />
    
<% end %>
</ul>

<%= link_to "Create a New Article", new_article_path %><br>
<%= link_to "Create a New Tag", new_tag_path %><br>
<%= link_to 'Tags List', tags_path %>

app/views/articles/new.html.erb
<h1>Create a new Article</h1>

<%= render partial: 'form' %>

<%= link_to "<< Back to Articles List", articles_path %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>Tags:
   <% @article.tags.each do |tag| %>
     <%= link_to tag.name, tag_path(tag) %>
    <% end %>
</p>
<p><%= @article.body %></p>

<h3>Comments (<%= @article.comments.count %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>
<%= link_to 'Edit Article', edit_article_path(@article) %> ||
<%= link_to "Delete Article", article_path(@article), method: :delete, data: {confirm: 'Really want to delete it?'} %> ||
<%= link_to "<< Back to Articles List", articles_path %>

app/views/comments/_form.html.erb
<h3>Add a new comment</h3>
<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :your_name %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :your_comment %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>
<% @tags.each do |tag| %>
  <%= link_to tag.name, tag_path(tag) %>
<% end %>
<br />
<br />
<br />
<p><%= link_to 'Add new Tag', new_tag_path(tag) %></p>
<p><%= link_to '<< Back to Articles List', root_path %></p>

app/views/tags/new.html.erb
<%= form_for(@tag) do |f| %>
  <ul>
  <% @tag.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :tag_name %><br />
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>
<br />
<br />
<br />
<br />

<p><%= link_to '<<Delete this tag', tag_path(@tag), method: :delete, data: {confirm: 'Really want to delete it?'} %></p>
<p><%= link_to '<<Back to Articles List', root_path %></p>